# Server configuration
server:
  port: 8089
  contextPath:

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:  
    url : jdbc:mysql://localhost:3306/mid_practice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver 
    
  jpa:   
    show-sql : true 
    open-in-view : true
   # hibernate:      
   #   ddl-auto: update      
   # naming:        
   #     physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy    
   #     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
    
  

    
 
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  supercode: "99999"
  route:
    authentication:
      path: /api/user/ 
      register: /api/user/register/
#      refresh:

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
#spring.boot.admin.url: http://localhost:8080


